version: 0.2
phases:
  build:
    commands:
      - aws deploy push --application-name ec2-cicd-app --s3-location s3://test-ec2-cicd-artifact/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src